#!/scratch/bin/ruby
require "socket"

socket = UNIXSocket.open "/tmp/fake_mozart.socket"

loop do 
  header = socket.gets
  if header =~ /^<(\w+) (\d+)>\n$/
    body = socket.read $2.to_i
    File.open("fake_mozart_params.test", "w") do |file|
      file << body
    end
  end
  begin
    socket << "<keepfocus 0>\n"
  rescue Errno::EPIPE
  end
end
