#!/scratch/bin/ruby
require "socket"

socket = UNIXSocket.open "/tmp/no_respond.socket"

# this first one is to respond to the request when load_application is called
socket << "<keepfocus 0>\n"

Signal.trap("USR1") do
  socket << "<keepfocus 0>\n"
end

loop { sleep 10 }
