#!/scratch/bin/ruby
$0 = "clock"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "socket"
require "spandex/application"
require "spandex/card"

class CurrentTime < Spandex::Card
  top_left :back

  def show
    render_every 1, do
      "<button position=top_left>Back</button>
       <text y=10 x=15>
         #{Time.now.strftime("%H:%M %S").center(20, " ")}
       </text>
       <text y=25 x=15>
        #{Time.now.strftime("%d %B %Y").center(20, " ")}
       </text>"
    end
  end
end

class Clock < Spandex::Application
  entry_point :current_time
end

Clock.new.run
