#!/usr/bin/ruby
require "socket"

@socket = UNIXSocket.open "/tmp/clock.socket"

def respond_keep_focus
  @socket << "<keepfocus 0>\n"
  @socket.flush
end

def respond_close
  @socket << "<closing 0>\n"
  @socket.flush
end

def render_clock
  markup = "<button position=\"top_left\">Back</button><text x=\"30\" y=\"25\">#{Time.now}</text>"
  @socket << "<render #{markup.length}>\n#{markup}"
end

Thread.new do
  loop do
    render_clock
    sleep 1
  end
end

loop do
  header = @socket.gets
  if header =~ /^<(\w+) (\d{1,4})>\n$/
    button = @socket.read $2.to_i
    case button.chomp
    when "top_left"
      respond_close
      exit
    else
      respond_keep_focus
    end
  end
end
