#!/scratch/bin/ruby
$0 = "clock"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "spandex/application"
require "spandex/card"

class CurrentTime < Spandex::Card
  top_left :back

  def show
    render_every 1, do
      %{
        <button position="top_left">Back</button>
        <text y="10" size="huge" halign="centre">#{Time.now.strftime("%H:%M")}</text>
        <text y="40" halign="centre"> #{Time.now.strftime("%d %B %Y")}</text>
      }
    end
  end
end

class Clock < Spandex::Application
  entry_point :current_time
end

Clock.new.run
