#!/scratch/bin/ruby
$0 = "internet_radio"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "spandex/application"
require "spandex/card"
require "spandex/list"

class Channels < Spandex::ListCard
  top_left :back

  jog_wheel_button method: -> do
    pass_focus application: "mozart", method: "play_stream", params: @apps[@list.selected]
  end

  # TODO: the .asx files for the BBC channels have multiple streams in them,
  # presumably to provide fallback. We should probably add all of these to the
  # play queue.
  def after_initialize
    @apps = {}
    @apps["BBC Radio 1"] = "mms://wmlive-acl.bbc.co.uk/wms/bbc_ami/radio1/radio1_bb_live_ep1_sl0?BBC-UID=04db42d7a6c617e205489956716f9eca1f4e7f0c806011a4b4ef5811efcb96f5&amp;SSO2-UID="
    @apps["BBC Radio 4"] = "mms://wmlive-acl.bbc.co.uk/wms/bbc_ami/radio4/radio4_bb_live_ep1_sl0?BBC-UID=c4ab2297a6262b8d7cd30b240194bdbd2ea76dc9c090424162f83024230c80d8&amp;SSO2-UID="
    @apps["Galaxy"] = "http://media-ice.musicradio.com:80/GalaxyScotland"
    @apps["Two Lochs"] = "http://icecast.commedia.org.uk:8000/twolochs.mp3"
    @list = Spandex::List.new @apps.keys
  end

  def show
    render %{
      <button position="top_left">Back</button>
      <title>Internet radio</title>
      #{@list.to_s}
    }
  end
end

class InternetRadio < Spandex::Application
  entry_point Channels
end

InternetRadio.new.run
