#!/scratch/bin/ruby
$0 = "main_menu"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "spandex/application"
require "spandex/card"
require "spandex/list"

class Menu < Spandex::ListCard

  top_right method: -> do
    if @mozart_playing
      pass_focus application: "mozart"
    end
  end

  jog_wheel_button method: -> do
    pass_focus application: @apps[@list.selected]
  end

  def after_initialize
    @apps = {}
    @apps["Music"] = "messier"
    @apps["Internet radio"] = "internet_radio"
    @apps["Clock"] = "clock"
    @apps["Stats"] = "stats"
    @list = Spandex::List.new @apps.keys
    @mozart_playing = false
    Signal.trap("USR1") { @mozart_playing = true }
  end

  def show
    if @mozart_playing
      render %{
        <button position="top_right">Now playing</button>
        #{@list.to_s}
      }
    else
      render @list.to_s
    end
  end
end

class MainMenu < Spandex::Application
  entry_point Menu
  can_run_in_background
end

MainMenu.new.run
