#!/scratch/bin/ruby
$0 = "main_menu"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "spandex/application"
require "spandex/card"
require "spandex/list"

class Menu < Spandex::ListCard

  top_right method: -> do
    pass_focus application: "mozart"
  end

  jog_wheel_button method: -> do
    pass_focus application: @apps[@list.selected]
  end

  def after_initialize
    @apps = {}
    @apps["Music"] = "messier"
    @apps["Internet radio"] = "internet_radio"
    @apps["Clock"] = "clock"
    @apps["Stats"] = "stats"
    @list = Spandex::List.new @apps.keys
  end

  def show
    render %{
      <button position="top_right">Now playing</button>
      #{@list.to_s}
    }
  end
end

class MainMenu < Spandex::Application
  entry_point :menu
end

MainMenu.new.run
