#!/scratch/bin/ruby
$0 = "main_menu"
$LOAD_PATH.unshift "#{ENV["PROJECT_X_BASE"]}/lib/"

require "socket"
require "spandex/application"
require "spandex/card"
require "spandex/list"

class Menu < Spandex::ListCard
  jog_wheel_button method: -> do
    pass_focus({ application: @apps[@list.selected] })
  end

  def after_initialize
    @apps = {}
    @apps["Music"] = "messier"
    @apps["Clock"] = "clock"
    @list = Spandex::List.new @apps.keys
  end

  def show
    render @list.to_s
  end
end

class MainMenu < Spandex::Application
  entry_point :menu
end

MainMenu.new.run
